ARG REGISTRY=docker.io
ARG DOWNLOAD_URL=https://fw.gl-inet.com/firmware/mt1300/release4/openwrt-mt1300-4.3.19-0823-1724384445.bin
ARG FW2TAR=${REGISTRY}/rehosting/fw2tar:f44361d4c64e9e6f54d940cb2637bf9283961a29
ARG PENGUIN=${REGISTRY}/rehosting/penguin:v1.2.25

FROM ${FW2TAR} AS prep
ARG DOWNLOAD_URL
RUN apt-get update && apt-get install wget
RUN wget -O /input_file ${DOWNLOAD_URL}
RUN fakeroot fw2tar /input_file
RUN mv /*.rootfs.tar.gz /project.rootfs.tar.gz

FROM ${PENGUIN} AS run
WORKDIR /workspace
COPY --from=prep /project.rootfs.tar.gz /tmp
RUN penguin init /tmp/project.rootfs.tar.gz --output_base / --output /workspace
COPY patch_pseudofiles.yaml /workspace
RUN chmod -R 777 /workspace
CMD [ "penguin", "run", "."]

# FROM run AS test
# COPY patch_test.yaml /workspace/