ARG REGISTRY=docker.io
ARG DOWNLOAD_URL=https://www.draytek.co.uk/support/downloads/vigor-2960?task=download.send&id=3454:v2960-1516&catid=341
ARG FW2TAR=${REGISTRY}/rehosting/fw2tar:f44361d4c64e9e6f54d940cb2637bf9283961a29
ARG PENGUIN=${REGISTRY}/rehosting/penguin:v1.2.24

FROM ${FW2TAR} AS prep
ARG DOWNLOAD_URL
RUN apt-get update && apt-get -y install curl
RUN curl -k ${DOWNLOAD_URL} --output /input_file
RUN fakeroot fw2tar /input_file
RUN mv /*.rootfs.tar.gz /project.rootfs.tar.gz

FROM ${PENGUIN} AS run
WORKDIR /workspace
COPY --from=prep /project.rootfs.tar.gz /tmp
RUN penguin init /tmp/project.rootfs.tar.gz --output_base / --output /workspace
COPY patch_dev.yaml /workspace/
RUN chmod -R 777 /workspace
CMD [ "penguin", "run", "."]

FROM run AS test
COPY patch_test.yaml /workspace/