ARG REGISTRY=docker.io
ARG DOWNLOAD_URL=https://panda.re/secret/stridelinx.bin
ARG FW2TAR=${REGISTRY}/rehosting/fw2tar:52e596c0fab25b12d6de4a3e666bbd57af4dd6b8
ARG PENGUIN=${REGISTRY}/rehosting/penguin:v2.1.6

FROM ${FW2TAR} AS prep
ARG DOWNLOAD_URL
RUN apt-get update && apt-get install wget
RUN wget -O /input_file ${DOWNLOAD_URL}
RUN fakeroot fw2tar /input_file
RUN mv /*.rootfs.tar.gz /project.rootfs.tar.gz

FROM ${PENGUIN} AS run
WORKDIR /workspace
COPY --from=prep /project.rootfs.tar.gz /tmp
RUN penguin init /tmp/project.rootfs.tar.gz --output_base / --output /workspace
COPY patch_stride.yaml /workspace
RUN chmod -R 777 /workspace
CMD [ "penguin", "run", "."]

FROM run AS test
COPY patch_test.yaml /workspace
