ARG REGISTRY=docker.io
ARG DOWNLOAD_URL=https://downloads.trendnet.com/tv-ip201w/firmware/fw_tv-ip201_201w(v2.00.110).zip
ARG FW2TAR=${REGISTRY}/rehosting/fw2tar:38455f876dc84f2b5a3b501455e48a50079649f0
ARG PENGUIN=${REGISTRY}/rehosting/penguin:v1.4.20

FROM ${FW2TAR} AS prep
ARG DOWNLOAD_URL
RUN apt-get update && apt-get install wget
RUN wget -O /input_file ${DOWNLOAD_URL}
RUN fakeroot fw2tar /input_file
RUN mv /*.rootfs.tar.gz /project.rootfs.tar.gz

FROM ${PENGUIN} AS run
WORKDIR /workspace
COPY --from=prep /project.rootfs.tar.gz /tmp
RUN penguin init /tmp/project.rootfs.tar.gz --output_base / --output /workspace

# add patches
COPY patch_netdev.yaml /workspace
RUN chmod -R 777 /workspace

CMD [ "penguin", "run", "."]

FROM run AS test
COPY patch_test.yaml /workspace/